# -*- coding: utf-8 -*-
"""image.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1vg6531xreEakK6pKW98Vccv8J0OkPuW_
"""

from google.colab import drive
drive.mount('/content/drive')

path = '/content/drive/MyDrive/Abuzer/data/Data set/'

import os
# print(dir(os))
os.listdir(path+os.listdir(path)[0])

import os
import cv2
for dir in os.listdir(path):
  # print(dir)
  folder = '/content/drive/MyDrive/Abuzer/data/images/'
  if dir not in os.listdir(folder):
    os.mkdir(folder+dir)
  count=1
  image_path = folder+dir+'/'
  # print(image_path)
  for video in os.listdir(path+dir):
    video_path = path+dir+'/'+video
    # print(video_path)
    vidcap = cv2.VideoCapture(video_path)
    
   
    def getFrame(sec):
        vidcap.set(cv2.CAP_PROP_POS_MSEC,sec*1000)
        hasFrames,image = vidcap.read()
        if hasFrames:
            cv2.imwrite(image_path+"image"+str(count)+".jpg", image)     # save frame as JPG file
        return hasFrames
    sec = 0
    frameRate = 1 #//it will capture image in each 0.5 second
    success = getFrame(sec)
    while success:
        count = count + 1
        sec = sec + frameRate
        sec = round(sec, 2)
        success = getFrame(sec)
  # print(dir)

